/**
 * Country presets. Generated by scripts/update-regions.mjs; edit that, not this list.
 *
 * - `intensity`: lifecycle carbon intensity of grid electricity in kg CO2e/kWh,
 *   latest year available from Ember via Our World in Data.
 * - `price`: typical household tariff in local currency per kWh, from
 *   GlobalPetrolPrices, converted at exchange rates of 2026-09-30.
 *   Tariffs change often and vary by supplier, so the UI always asks people
 *   to check their own bill.
 */
export interface Region {
	id: string;
	name: string;
	currency: string;
	locale: string;
	intensity: number;
	price: number;
	distance: "km" | "mi";
	/** ISO 3166 numeric code, as used by the world map data. Some small
	 *  countries only appear on the detailed map shown when zoomed in. */
	iso?: string;
}

export const REGIONS: Region[] = [
	{ id: "world", name: "World average", currency: "USD", locale: "en-US", intensity: 0.458, price: 0.17, distance: "km" },
	{ id: "eu", name: "European Union average", currency: "EUR", locale: "en-IE", intensity: 0.21, price: 0.29, distance: "km" },
	{ id: "af", name: "Afghanistan", currency: "AFN", locale: "en-AF", intensity: 0.131, price: 3.36, distance: "km", iso: "004" },
	{ id: "al", name: "Albania", currency: "ALL", locale: "sq-AL", intensity: 0.025, price: 9.64, distance: "km", iso: "008" },
	{ id: "dz", name: "Algeria", currency: "DZD", locale: "en-DZ", intensity: 0.633, price: 5.48, distance: "km", iso: "012" },
	{ id: "ao", name: "Angola", currency: "AOA", locale: "pt-AO", intensity: 0.185, price: 15, distance: "km", iso: "024" },
	{ id: "ar", name: "Argentina", currency: "ARS", locale: "es-AR", intensity: 0.346, price: 135, distance: "km", iso: "032" },
	{ id: "am", name: "Armenia", currency: "AMD", locale: "hy-AM", intensity: 0.212, price: 41, distance: "km", iso: "051" },
	{ id: "aw", name: "Aruba", currency: "AWG", locale: "nl-AW", intensity: 0.55, price: 0.378, distance: "km", iso: "533" },
	{ id: "au", name: "Australia", currency: "AUD", locale: "en-AU", intensity: 0.525, price: 0.371, distance: "km", iso: "036" },
	{ id: "at", name: "Austria", currency: "EUR", locale: "de-AT", intensity: 0.117, price: 0.311, distance: "km", iso: "040" },
	{ id: "az", name: "Azerbaijan", currency: "AZN", locale: "az-AZ", intensity: 0.632, price: 0.082, distance: "km", iso: "031" },
	{ id: "bs", name: "Bahamas", currency: "BSD", locale: "en-BS", intensity: 0.653, price: 0.348, distance: "km", iso: "044" },
	{ id: "bh", name: "Bahrain", currency: "BHD", locale: "en-BH", intensity: 0.902, price: 0.018, distance: "km", iso: "048" },
	{ id: "bd", name: "Bangladesh", currency: "BDT", locale: "en-BD", intensity: 0.696, price: 7.75, distance: "km", iso: "050" },
	{ id: "bb", name: "Barbados", currency: "BBD", locale: "en-BB", intensity: 0.595, price: 0.628, distance: "km", iso: "052" },
	{ id: "by", name: "Belarus", currency: "BYN", locale: "be-BY", intensity: 0.309, price: 0.262, distance: "km", iso: "112" },
	{ id: "be", name: "Belgium", currency: "EUR", locale: "nl-BE", intensity: 0.15, price: 0.358, distance: "km", iso: "056" },
	{ id: "bz", name: "Belize", currency: "BZD", locale: "en-BZ", intensity: 0.17, price: 0.438, distance: "km", iso: "084" },
	{ id: "bm", name: "Bermuda", currency: "BMD", locale: "en-BM", intensity: 0.639, price: 0.465, distance: "km", iso: "060" },
	{ id: "bt", name: "Bhutan", currency: "BTN", locale: "en-BT", intensity: 0.024, price: 1.44, distance: "km", iso: "064" },
	{ id: "ba", name: "Bosnia and Herzegovina", currency: "BAM", locale: "bs-BA", intensity: 0.571, price: 0.186, distance: "km", iso: "070" },
	{ id: "bw", name: "Botswana", currency: "BWP", locale: "en-BW", intensity: 0.851, price: 1.32, distance: "km", iso: "072" },
	{ id: "br", name: "Brazil", currency: "BRL", locale: "pt-BR", intensity: 0.11, price: 0.856, distance: "km", iso: "076" },
	{ id: "bg", name: "Bulgaria", currency: "EUR", locale: "bg-BG", intensity: 0.276, price: 0.137, distance: "km", iso: "100" },
	{ id: "bf", name: "Burkina Faso", currency: "XOF", locale: "fr-BF", intensity: 0.562, price: 120, distance: "km", iso: "854" },
	{ id: "cv", name: "Cabo Verde", currency: "CVE", locale: "pt-CV", intensity: 0.462, price: 32, distance: "km", iso: "132" },
	{ id: "kh", name: "Cambodia", currency: "KHR", locale: "km-KH", intensity: 0.499, price: 605, distance: "km", iso: "116" },
	{ id: "cm", name: "Cameroon", currency: "XAF", locale: "en-CM", intensity: 0.226, price: 48.5, distance: "km", iso: "120" },
	{ id: "ca", name: "Canada", currency: "CAD", locale: "en-CA", intensity: 0.191, price: 0.174, distance: "km", iso: "124" },
	{ id: "ky", name: "Cayman Islands", currency: "KYD", locale: "en-KY", intensity: 0.634, price: 0.342, distance: "km", iso: "136" },
	{ id: "cl", name: "Chile", currency: "CLP", locale: "es-CL", intensity: 0.289, price: 220, distance: "km", iso: "152" },
	{ id: "cn", name: "China", currency: "CNY", locale: "zh-CN", intensity: 0.525, price: 0.511, distance: "km", iso: "156" },
	{ id: "co", name: "Colombia", currency: "COP", locale: "es-CO", intensity: 0.187, price: 695, distance: "km", iso: "170" },
	{ id: "cr", name: "Costa Rica", currency: "CRC", locale: "es-CR", intensity: 0.024, price: 77.5, distance: "km", iso: "188" },
	{ id: "hr", name: "Croatia", currency: "EUR", locale: "hr-HR", intensity: 0.159, price: 0.16, distance: "km", iso: "191" },
	{ id: "cu", name: "Cuba", currency: "CUP", locale: "es-CU", intensity: 0.643, price: 0.336, distance: "km", iso: "192" },
	{ id: "cy", name: "Cyprus", currency: "EUR", locale: "el-CY", intensity: 0.489, price: 0.302, distance: "km", iso: "196" },
	{ id: "cz", name: "Czechia", currency: "CZK", locale: "cs-CZ", intensity: 0.401, price: 7.56, distance: "km", iso: "203" },
	{ id: "cd", name: "Democratic Republic of the Congo", currency: "CDF", locale: "fr-CD", intensity: 0.028, price: 155, distance: "km", iso: "180" },
	{ id: "dk", name: "Denmark", currency: "DKK", locale: "da-DK", intensity: 0.114, price: 2.34, distance: "km", iso: "208" },
	{ id: "do", name: "Dominican Republic", currency: "DOP", locale: "es-DO", intensity: 0.537, price: 6.73, distance: "km", iso: "214" },
	{ id: "ec", name: "Ecuador", currency: "USD", locale: "es-EC", intensity: 0.159, price: 0.097, distance: "km", iso: "218" },
	{ id: "eg", name: "Egypt", currency: "EGP", locale: "en-EG", intensity: 0.563, price: 1.2, distance: "km", iso: "818" },
	{ id: "sv", name: "El Salvador", currency: "USD", locale: "es-SV", intensity: 0.139, price: 0.254, distance: "km", iso: "222" },
	{ id: "ee", name: "Estonia", currency: "EUR", locale: "et-EE", intensity: 0.319, price: 0.257, distance: "km", iso: "233" },
	{ id: "sz", name: "Eswatini", currency: "SZL", locale: "en-SZ", intensity: 0.131, price: 2.12, distance: "km", iso: "748" },
	{ id: "et", name: "Ethiopia", currency: "ETB", locale: "am-ET", intensity: 0.023, price: 0.975, distance: "km", iso: "231" },
	{ id: "fi", name: "Finland", currency: "EUR", locale: "fi-FI", intensity: 0.057, price: 0.154, distance: "km", iso: "246" },
	{ id: "fr", name: "France", currency: "EUR", locale: "fr-FR", intensity: 0.041, price: 0.243, distance: "km", iso: "250" },
	{ id: "ga", name: "Gabon", currency: "XAF", locale: "fr-GA", intensity: 0.523, price: 120, distance: "km", iso: "266" },
	{ id: "ge", name: "Georgia", currency: "GEL", locale: "ka-GE", intensity: 0.146, price: 0.174, distance: "km", iso: "268" },
	{ id: "de", name: "Germany", currency: "EUR", locale: "de-DE", intensity: 0.33, price: 0.358, distance: "km", iso: "276" },
	{ id: "gh", name: "Ghana", currency: "GHS", locale: "en-GH", intensity: 0.469, price: 1.72, distance: "km", iso: "288" },
	{ id: "gr", name: "Greece", currency: "EUR", locale: "el-GR", intensity: 0.315, price: 0.224, distance: "km", iso: "300" },
	{ id: "gt", name: "Guatemala", currency: "GTQ", locale: "es-GT", intensity: 0.301, price: 2.28, distance: "km", iso: "320" },
	{ id: "hn", name: "Honduras", currency: "HNL", locale: "es-HN", intensity: 0.322, price: 6.2, distance: "km", iso: "340" },
	{ id: "hk", name: "Hong Kong", currency: "HKD", locale: "zh-HK", intensity: 0.675, price: 1.44, distance: "km", iso: "344" },
	{ id: "hu", name: "Hungary", currency: "HUF", locale: "hu-HU", intensity: 0.163, price: 36, distance: "km", iso: "348" },
	{ id: "is", name: "Iceland", currency: "ISK", locale: "is-IS", intensity: 0.028, price: 21.5, distance: "km", iso: "352" },
	{ id: "in", name: "India", currency: "INR", locale: "en-IN", intensity: 0.67, price: 7.4, distance: "km", iso: "356" },
	{ id: "id", name: "Indonesia", currency: "IDR", locale: "id-ID", intensity: 0.68, price: 1615, distance: "km", iso: "360" },
	{ id: "iq", name: "Iraq", currency: "IQD", locale: "en-IQ", intensity: 0.683, price: 19.5, distance: "km", iso: "368" },
	{ id: "ie", name: "Ireland", currency: "EUR", locale: "en-IE", intensity: 0.257, price: 0.397, distance: "km", iso: "372" },
	{ id: "il", name: "Israel", currency: "ILS", locale: "he-IL", intensity: 0.493, price: 0.568, distance: "km", iso: "376" },
	{ id: "it", name: "Italy", currency: "EUR", locale: "it-IT", intensity: 0.285, price: 0.365, distance: "km", iso: "380" },
	{ id: "ci", name: "Ivory Coast", currency: "XOF", locale: "fr-CI", intensity: 0.405, price: 76.5, distance: "km", iso: "384" },
	{ id: "jm", name: "Jamaica", currency: "JMD", locale: "en-JM", intensity: 0.563, price: 46, distance: "km", iso: "388" },
	{ id: "jp", name: "Japan", currency: "JPY", locale: "ja-JP", intensity: 0.477, price: 35.5, distance: "km", iso: "392" },
	{ id: "jo", name: "Jordan", currency: "JOD", locale: "en-JO", intensity: 0.53, price: 0.064, distance: "km", iso: "400" },
	{ id: "kz", name: "Kazakhstan", currency: "KZT", locale: "kk-KZ", intensity: 0.805, price: 25, distance: "km", iso: "398" },
	{ id: "ke", name: "Kenya", currency: "KES", locale: "en-KE", intensity: 0.095, price: 28.5, distance: "km", iso: "404" },
	{ id: "kw", name: "Kuwait", currency: "KWD", locale: "en-KW", intensity: 0.635, price: 0.012, distance: "km", iso: "414" },
	{ id: "kg", name: "Kyrgyzstan", currency: "KGS", locale: "ky-KG", intensity: 0.153, price: 1.31, distance: "km", iso: "417" },
	{ id: "la", name: "Laos", currency: "LAK", locale: "lo-LA", intensity: 0.232, price: 755, distance: "km", iso: "418" },
	{ id: "lv", name: "Latvia", currency: "EUR", locale: "lv-LV", intensity: 0.139, price: 0.247, distance: "km", iso: "428" },
	{ id: "ls", name: "Lesotho", currency: "LSL", locale: "en-LS", intensity: 0.021, price: 1.77, distance: "km", iso: "426" },
	{ id: "lt", name: "Lithuania", currency: "EUR", locale: "lt-LT", intensity: 0.138, price: 0.251, distance: "km", iso: "440" },
	{ id: "lu", name: "Luxembourg", currency: "EUR", locale: "fr-LU", intensity: 0.123, price: 0.23, distance: "km", iso: "442" },
	{ id: "mg", name: "Madagascar", currency: "MGA", locale: "fr-MG", intensity: 0.432, price: 570, distance: "km", iso: "450" },
	{ id: "mw", name: "Malawi", currency: "MWK", locale: "en-MW", intensity: 0.055, price: 155, distance: "km", iso: "454" },
	{ id: "my", name: "Malaysia", currency: "MYR", locale: "ms-MY", intensity: 0.602, price: 0.204, distance: "km", iso: "458" },
	{ id: "mv", name: "Maldives", currency: "MVR", locale: "dv-MV", intensity: 0.612, price: 1.61, distance: "km", iso: "462" },
	{ id: "ml", name: "Mali", currency: "XOF", locale: "fr-ML", intensity: 0.539, price: 130, distance: "km", iso: "466" },
	{ id: "mt", name: "Malta", currency: "EUR", locale: "mt-MT", intensity: 0.484, price: 0.13, distance: "km", iso: "470" },
	{ id: "mu", name: "Mauritius", currency: "MUR", locale: "en-MU", intensity: 0.642, price: 6.42, distance: "km", iso: "480" },
	{ id: "mx", name: "Mexico", currency: "MXN", locale: "es-MX", intensity: 0.474, price: 1.96, distance: "km", iso: "484" },
	{ id: "md", name: "Moldova", currency: "MDL", locale: "ro-MD", intensity: 0.633, price: 3.17, distance: "km", iso: "498" },
	{ id: "me", name: "Montenegro", currency: "EUR", locale: "sr-ME", intensity: 0.264, price: 0.106, distance: "km", iso: "499" },
	{ id: "ma", name: "Morocco", currency: "MAD", locale: "en-MA", intensity: 0.596, price: 1.17, distance: "km", iso: "504" },
	{ id: "mz", name: "Mozambique", currency: "MZN", locale: "pt-MZ", intensity: 0.129, price: 8.1, distance: "km", iso: "508" },
	{ id: "mm", name: "Myanmar", currency: "MMK", locale: "en-MM", intensity: 0.503, price: 52.5, distance: "mi", iso: "104" },
	{ id: "na", name: "Namibia", currency: "NAD", locale: "en-NA", intensity: 0.049, price: 2.35, distance: "km", iso: "516" },
	{ id: "np", name: "Nepal", currency: "NPR", locale: "en-NP", intensity: 0.024, price: 6.46, distance: "km", iso: "524" },
	{ id: "nl", name: "Netherlands", currency: "EUR", locale: "nl-NL", intensity: 0.254, price: 0.252, distance: "km", iso: "528" },
	{ id: "nz", name: "New Zealand", currency: "NZD", locale: "en-NZ", intensity: 0.093, price: 0.376, distance: "km", iso: "554" },
	{ id: "ni", name: "Nicaragua", currency: "NIO", locale: "es-NI", intensity: 0.301, price: 6.46, distance: "km", iso: "558" },
	{ id: "ng", name: "Nigeria", currency: "NGN", locale: "en-NG", intensity: 0.456, price: 48, distance: "km", iso: "566" },
	{ id: "mk", name: "North Macedonia", currency: "MKD", locale: "mk-MK", intensity: 0.441, price: 6.93, distance: "km", iso: "807" },
	{ id: "no", name: "Norway", currency: "NOK", locale: "nb-NO", intensity: 0.028, price: 1.58, distance: "km", iso: "578" },
	{ id: "om", name: "Oman", currency: "OMR", locale: "en-OM", intensity: 0.544, price: 0.012, distance: "km", iso: "512" },
	{ id: "pk", name: "Pakistan", currency: "PKR", locale: "en-PK", intensity: 0.347, price: 17.5, distance: "km", iso: "586" },
	{ id: "pa", name: "Panama", currency: "PAB", locale: "es-PA", intensity: 0.221, price: 0.176, distance: "km", iso: "591" },
	{ id: "py", name: "Paraguay", currency: "PYG", locale: "es-PY", intensity: 0.025, price: 325, distance: "km", iso: "600" },
	{ id: "pe", name: "Peru", currency: "PEN", locale: "es-PE", intensity: 0.238, price: 0.639, distance: "km", iso: "604" },
	{ id: "ph", name: "Philippines", currency: "PHP", locale: "en-PH", intensity: 0.588, price: 13, distance: "km", iso: "608" },
	{ id: "pl", name: "Poland", currency: "PLN", locale: "pl-PL", intensity: 0.589, price: 0.909, distance: "km", iso: "616" },
	{ id: "pt", name: "Portugal", currency: "EUR", locale: "pt-PT", intensity: 0.128, price: 0.211, distance: "km", iso: "620" },
	{ id: "qa", name: "Qatar", currency: "QAR", locale: "en-QA", intensity: 0.582, price: 0.116, distance: "km", iso: "634" },
	{ id: "ro", name: "Romania", currency: "RON", locale: "ro-RO", intensity: 0.251, price: 1.03, distance: "km", iso: "642" },
	{ id: "ru", name: "Russia", currency: "RUB", locale: "ru-RU", intensity: 0.45, price: 5.8, distance: "km", iso: "643" },
	{ id: "rw", name: "Rwanda", currency: "RWF", locale: "rw-RW", intensity: 0.354, price: 310, distance: "km", iso: "646" },
	{ id: "sa", name: "Saudi Arabia", currency: "SAR", locale: "en-SA", intensity: 0.692, price: 0.195, distance: "km", iso: "682" },
	{ id: "sn", name: "Senegal", currency: "XOF", locale: "fr-SN", intensity: 0.54, price: 105, distance: "km", iso: "686" },
	{ id: "rs", name: "Serbia", currency: "RSD", locale: "sr-RS", intensity: 0.696, price: 13.5, distance: "km", iso: "688" },
	{ id: "sl", name: "Sierra Leone", currency: "SLE", locale: "en-SL", intensity: 0.048, price: 5.71, distance: "km", iso: "694" },
	{ id: "sg", name: "Singapore", currency: "SGD", locale: "en-SG", intensity: 0.497, price: 0.298, distance: "km", iso: "702" },
	{ id: "sk", name: "Slovakia", currency: "EUR", locale: "sk-SK", intensity: 0.095, price: 0.19, distance: "km", iso: "703" },
	{ id: "si", name: "Slovenia", currency: "EUR", locale: "sl-SI", intensity: 0.183, price: 0.201, distance: "km", iso: "705" },
	{ id: "za", name: "South Africa", currency: "ZAR", locale: "en-ZA", intensity: 0.699, price: 3.43, distance: "km", iso: "710" },
	{ id: "kr", name: "South Korea", currency: "KRW", locale: "ko-KR", intensity: 0.417, price: 170, distance: "km", iso: "410" },
	{ id: "es", name: "Spain", currency: "EUR", locale: "es-ES", intensity: 0.154, price: 0.225, distance: "km", iso: "724" },
	{ id: "lk", name: "Sri Lanka", currency: "LKR", locale: "si-LK", intensity: 0.329, price: 37.5, distance: "km", iso: "144" },
	{ id: "sd", name: "Sudan", currency: "SDG", locale: "en-SD", intensity: 0.154, price: 7.64, distance: "km", iso: "729" },
	{ id: "sr", name: "Suriname", currency: "SRD", locale: "nl-SR", intensity: 0.322, price: 1.89, distance: "km", iso: "740" },
	{ id: "se", name: "Sweden", currency: "SEK", locale: "sv-SE", intensity: 0.035, price: 2.43, distance: "km", iso: "752" },
	{ id: "ch", name: "Switzerland", currency: "CHF", locale: "de-CH", intensity: 0.039, price: 0.306, distance: "km", iso: "756" },
	{ id: "tw", name: "Taiwan", currency: "TWD", locale: "zh-TW", intensity: 0.633, price: 3.12, distance: "km", iso: "158" },
	{ id: "tz", name: "Tanzania", currency: "TZS", locale: "sw-TZ", intensity: 0.345, price: 240, distance: "km", iso: "834" },
	{ id: "th", name: "Thailand", currency: "THB", locale: "th-TH", intensity: 0.546, price: 4.26, distance: "km", iso: "764" },
	{ id: "tg", name: "Togo", currency: "XOF", locale: "fr-TG", intensity: 0.423, price: 115, distance: "km", iso: "768" },
	{ id: "tt", name: "Trinidad and Tobago", currency: "TTD", locale: "en-TT", intensity: 0.682, price: 0.385, distance: "km", iso: "780" },
	{ id: "tn", name: "Tunisia", currency: "TND", locale: "en-TN", intensity: 0.56, price: 0.199, distance: "km", iso: "788" },
	{ id: "tr", name: "Türkiye", currency: "TRY", locale: "tr-TR", intensity: 0.475, price: 3.28, distance: "km", iso: "792" },
	{ id: "ug", name: "Uganda", currency: "UGX", locale: "en-UG", intensity: 0.059, price: 655, distance: "km", iso: "800" },
	{ id: "ua", name: "Ukraine", currency: "UAH", locale: "uk-UA", intensity: 0.25, price: 3.77, distance: "km", iso: "804" },
	{ id: "ae", name: "United Arab Emirates", currency: "AED", locale: "en-AE", intensity: 0.468, price: 0.294, distance: "km", iso: "784" },
	{ id: "gb", name: "United Kingdom", currency: "GBP", locale: "en-GB", intensity: 0.217, price: 0.304, distance: "mi", iso: "826" },
	{ id: "us", name: "United States", currency: "USD", locale: "en-US", intensity: 0.384, price: 0.188, distance: "mi", iso: "840" },
	{ id: "uy", name: "Uruguay", currency: "UYU", locale: "es-UY", intensity: 0.08, price: 10, distance: "km", iso: "858" },
	{ id: "uz", name: "Uzbekistan", currency: "UZS", locale: "uz-UZ", intensity: 1, price: 460, distance: "km", iso: "860" },
	{ id: "ve", name: "Venezuela", currency: "VES", locale: "es-VE", intensity: 0.086, price: 59.5, distance: "km", iso: "862" },
	{ id: "vn", name: "Vietnam", currency: "VND", locale: "vi-VN", intensity: 0.461, price: 2025, distance: "km", iso: "704" },
	{ id: "zm", name: "Zambia", currency: "ZMW", locale: "en-ZM", intensity: 0.12, price: 0.45, distance: "km", iso: "894" },
];

export const DEFAULT_REGION_ID = "us";

/** EU member states (ISO numeric), highlighted when "European Union average" is picked. */
export const EU_MEMBERS = new Set([
	"040", "056", "100", "191", "196", "203", "208", "233", "246", "250", "276", "300", "348",
	"372", "380", "428", "440", "442", "470", "528", "616", "620", "642", "703", "705", "724", "752",
]);

const BY_ID = new Map(REGIONS.map((r) => [r.id, r]));

export const getRegion = (id: string): Region =>
	BY_ID.get(id) ?? BY_ID.get(DEFAULT_REGION_ID)!;

/** Best guess at the visitor's country from the browser locale, e.g. "en-GB" -> "gb". */
export function guessRegionId(): string {
	if (typeof navigator === "undefined") return DEFAULT_REGION_ID;
	for (const tag of navigator.languages ?? [navigator.language]) {
		const country = tag.split("-")[1]?.toLowerCase();
		if (country && BY_ID.has(country)) return country;
	}
	return DEFAULT_REGION_ID;
}
